# Generated by Django 2.2.2 on 2019-06-22 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RES', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RIZ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=100)),
                ('add_adress', models.CharField(blank=True, max_length=200)),
                ('type_tp', models.IntegerField(choices=[(0, 'РП'), (1, 'ТП'), (2, 'КТП'), (3, 'МТП'), (4, 'БКТП')])),
                ('num_tp', models.IntegerField()),
                ('col_stt', models.IntegerField()),
                ('num_USPD', models.IntegerField(blank=True)),
                ('remarks_equipment', models.CharField(blank=True, max_length=200)),
                ('num_direct_dial', models.CharField(blank=True, max_length=20)),
                ('num_reserv_dial', models.CharField(blank=True, max_length=20)),
                ('GPS_latit', models.CharField(blank=True, max_length=20)),
                ('GPS_longit', models.CharField(blank=True, max_length=20)),
                ('RES', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RES', to='RES.RES')),
            ],
        ),
        migrations.AddIndex(
            model_name='riz',
            index=models.Index(fields=['adress'], name='RIZ_riz_adress_94d3e9_idx'),
        ),
        migrations.AddIndex(
            model_name='riz',
            index=models.Index(fields=['num_tp'], name='RIZ_riz_num_tp_9c2732_idx'),
        ),
    ]
