# Generated by Django 2.2.2 on 2019-06-22 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customr', '0001_initial'),
        ('RIZ', '0001_initial'),
        ('Ajust', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_akt', models.CharField(blank=True, max_length=6)),
                ('akt_date', models.DateField()),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('Ajust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ajust.Ajust')),
                ('Customr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customr.Customr')),
                ('RIZ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RIZ.RIZ')),
            ],
        ),
    ]
