# Generated by Django 2.2.2 on 2019-10-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commising', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='commising',
            index=models.Index(fields=['num_akt'], name='Commising_c_num_akt_9e99a0_idx'),
        ),
    ]
