# Generated by Django 2.2.2 on 2019-06-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('adress', models.CharField(blank=True, max_length=200)),
                ('remarks', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddIndex(
            model_name='res',
            index=models.Index(fields=['name'], name='RES_res_name_8e4e68_idx'),
        ),
    ]
